### ISSUE TITLE
guided execution does not know phiM

### ISSUE THREAD

**Issue by teambarrywhite** [cuichi23/delayCoupledDPLLnet#10]
Would you like to reset one of the following system parameters:
{
enable multiprocessing,
number of available cores to use,
parameter discretization for brute force method,
type of coupling fct,
intrinsic frequencies,
sample frequency time series,
standard deviation intrinsic frequency,
standard deviation coupling strength
}

[y]es/[n]o: n

Please specify simulation mode:

[1] single realization,
[2] statistics on noisy realizations,
[3] brute-force basin of attraction scan,
[4] single realization, adiabatic change of cLF.

Choice: 1

Please specify which parameters dependencies to be analyzed {coupling strength [K] in [Hz], LF cut-off freq [Fc] in [Hz], transmission [delay] in [s], loop filter GWN noise diff. const. [cLF] in [Hz^2]} : delay

Please specify the range in which delays should be simulated, start delay_s in [s] = 0

Please specify the range in which delays should be simulated, end delay_e in [s] = 1

Please specify the discretization steps in [s] ddelay = 0.1

Please specify topology from 1-dim [chain, ring], 2-dim [square-open, square-periodic, hexagon, octagon, hexagon-periodic, octagon-periodic] or mean-field [global] to be analyzed: global

Please specify the number [integer] of oscillators from [2, 1E5] in the network: 5

Please specify the m-twist number [integer] in [0, ..., 4] [dimless]: 0

Please specify as [float] the coupling strength [Hz]: 1

Please specify as [float] the cut-off frequency Fc [Hz]: 1

Please specify the diffusion constant [float, in Hz**2] for the GWN process on the frequencies of the DPLLs from the range [0, 10*K]: 0

Please specify the diffusion constant [float, in Hz**2] for the GWN process on CONTROL SIGNAL of the DPLLs from the range [0, 10*K]: 0

Please specify type delta-perturbation from {[1] manual, [2] all zero, [3] 1 of N perturbed, or [4] all perturbed according to a distribution}: 2

Please specify whether perturbation is provided in original [o] or rotated [r] phase space: r
No delta-perturbations, all set to zero!

(unchanged, i.e., only in-phase represented by R=1) order parameter for system after delta-perturbation:  1.0  and
twist number:  0

params <backports.configparser.ConfigParser object at 0x000000000A1270B8>
New parameter combinations with {N, F, K, Fc, delay, m, F_Omeg, ReLambda, ImLambda, Tsim, Nx, Ny, mx, my}:
 [[  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    2.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    3.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    3.00000000e-01   0.00000000e+00   1.81818182e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    4.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    4.00000000e-01   0.00000000e+00   1.53846154e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    5.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    5.00000000e-01   0.00000000e+00   1.33333333e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    6.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    6.00000000e-01   0.00000000e+00   1.17647059e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    7.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    7.00000000e-01   0.00000000e+00   1.05263158e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    8.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    8.00000000e-01   0.00000000e+00   9.52380952e-01  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    8.00000000e-01   0.00000000e+00   1.81818182e+00   2.77468537e+00
   -2.82843948e-19   9.01003057e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    8.00000000e-01   0.00000000e+00   1.90476190e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    9.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    9.00000000e-01   0.00000000e+00   8.69565217e-01  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    9.00000000e-01   0.00000000e+00   1.53846154e+00   2.77468537e+00
   -2.82843948e-19   9.01003057e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    9.00000000e-01   0.00000000e+00   1.73913043e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   0.00000000e+00   8.00000000e-01  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   0.00000000e+00   1.33333333e+00   2.77468537e+00
   -2.82843948e-19   9.01003057e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   0.00000000e+00   1.60000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]]

Please specify whether also linearly unstable solutions should be simulated, [y]es/[n]o: n

Could implement here to change TSim also in the case of parameter sweeps. Length para_mat:  22

START: python case_singleout.py global 5 1.0 1.0 0.0 0.0 0 50 0.0 1 5 1 0 -999 0.0[ 0.  0.  0.  0.  0.]
Tsim:  50.0
Parameters set, perturbations provided manually in rotated phase space of phases.
shift along the first axis in rotated phase space, equivalent to phase kick of all oscillators before simulation starts: phi`_0= 0.0

values of the initial phases in ROTATED phase space, i.e., last time-step of history set as initial condition: [[ 0.  0.  0.  0.  0.]]
values of initial phase in ORIGINAL phase space: [ 0.  0.  0.  0.  0.]

total simulation time in multiples of the eigentfrequency: 50

in case_singleout.singleout, F_Omeg: 0.0
NOTE: single realizations will be simulated for 2*Tsim to have enough waveforms after transients have decayed to plot spectral density.
Test single evaluation and plot phase and frequency time series, PROVIDE initial condition in ROTATED phase space!
Traceback (most recent call last):
  File "guided_execution.py", line 1784, in <module>
    singleRealization(params)
  File "guided_execution.py", line 921, in singleRealization
    pert, plot_out)
  File "D:\Benutzer\platz\Documents\Professional\Research\Coupled PLLs\github lucas\delayCoupledDPLLnet\case_singleout.py", line 252, in singleout
    data = simulatePllNetwork(mode, topology, couplingfct, F, Nsteps, dt, c, Fc, F_Omeg, K, N, k, delay, phiS, phiM, domega, diffconstK, cLF, Nx, Ny, kx, ky, plot_Phases_Freq) # initiates simulation and saves result in results container
UnboundLocalError: local variable 'phiM' referenced before assignment

# ###########################################################################

Would you like to reset one of the following system parameters:
{
enable multiprocessing,
number of available cores to use,
parameter discretization for brute force method,
type of coupling fct,
intrinsic frequencies,
sample frequency time series,
standard deviation intrinsic frequency,
standard deviation coupling strength
}

[y]es/[n]o: n

Please specify simulation mode:

[1] single realization,
[2] statistics on noisy realizations,
[3] brute-force basin of attraction scan,
[4] single realization, adiabatic change of cLF.

Choice: 1

Please specify which parameters dependencies to be analyzed {coupling strength [K] in [Hz], LF cut-off freq [Fc] in [Hz], transmission [delay] in [s], loop filter GWN noise diff. const. [cLF] in [Hz^2]} : delay

Please specify the range in which delays should be simulated, start delay_s in [s] = 0

Please specify the range in which delays should be simulated, end delay_e in [s] = 1

Please specify the discretization steps in [s] ddelay = 0.1

Please specify topology from 1-dim [chain, ring], 2-dim [square-open, square-periodic, hexagon, octagon, hexagon-periodic, octagon-periodic] or mean-field [global] to be analyzed: global

Please specify the number [integer] of oscillators from [2, 1E5] in the network: 5

Please specify the m-twist number [integer] in [0, ..., 4] [dimless]: 0

Please specify as [float] the coupling strength [Hz]: 1

Please specify as [float] the cut-off frequency Fc [Hz]: 1

Please specify the diffusion constant [float, in Hz**2] for the GWN process on the frequencies of the DPLLs from the range [0, 10*K]: 0

Please specify the diffusion constant [float, in Hz**2] for the GWN process on CONTROL SIGNAL of the DPLLs from the range [0, 10*K]: 0

Please specify type delta-perturbation from {[1] manual, [2] all zero, [3] 1 of N perturbed, or [4] all perturbed according to a distribution}: 2

Please specify whether perturbation is provided in original [o] or rotated [r] phase space: r
No delta-perturbations, all set to zero!

(unchanged, i.e., only in-phase represented by R=1) order parameter for system after delta-perturbation:  1.0  and
twist number:  0

params <backports.configparser.ConfigParser object at 0x000000000A2490F0>
New parameter combinations with {N, F, K, Fc, delay, m, F_Omeg, ReLambda, ImLambda, Tsim, Nx, Ny, mx, my}:
 [[  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    2.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    3.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    3.00000000e-01   0.00000000e+00   1.81818182e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    4.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    4.00000000e-01   0.00000000e+00   1.53846154e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    5.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    5.00000000e-01   0.00000000e+00   1.33333333e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    6.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    6.00000000e-01   0.00000000e+00   1.17647059e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    7.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    7.00000000e-01   0.00000000e+00   1.05263158e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    8.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    8.00000000e-01   0.00000000e+00   9.52380952e-01  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    8.00000000e-01   0.00000000e+00   1.81818182e+00   2.77468537e+00
   -2.82843948e-19   9.01003057e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    8.00000000e-01   0.00000000e+00   1.90476190e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    9.00000000e-01   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    9.00000000e-01   0.00000000e+00   8.69565217e-01  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    9.00000000e-01   0.00000000e+00   1.53846154e+00   2.77468537e+00
   -2.82843948e-19   9.01003057e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    9.00000000e-01   0.00000000e+00   1.73913043e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   0.00000000e+00   0.00000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   0.00000000e+00   8.00000000e-01  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   0.00000000e+00   1.33333333e+00   2.77468537e+00
   -2.82843948e-19   9.01003057e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]
 [  5.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   0.00000000e+00   1.60000000e+00  -3.14159265e+00
    3.90680647e+00   7.95774715e+00   5.00000000e+00   1.00000000e+00
    0.00000000e+00  -9.99000000e+02]]

Please specify whether also linearly unstable solutions should be simulated, [y]es/[n]o: y

Could implement here to change TSim also in the case of parameter sweeps. Length para_mat:  25

START: python case_singleout.py global 5 1.0 1.0 0.0 0.0 0 50 0.0 1 5 1 0 -999 0.0[ 0.  0.  0.  0.  0.]
Tsim:  50.0
Parameters set, perturbations provided manually in rotated phase space of phases.
shift along the first axis in rotated phase space, equivalent to phase kick of all oscillators before simulation starts: phi`_0= 0.0

values of the initial phases in ROTATED phase space, i.e., last time-step of history set as initial condition: [[ 0.  0.  0.  0.  0.]]
values of initial phase in ORIGINAL phase space: [ 0.  0.  0.  0.  0.]

total simulation time in multiples of the eigentfrequency: 50

in case_singleout.singleout, F_Omeg: 0.0
NOTE: single realizations will be simulated for 2*Tsim to have enough waveforms after transients have decayed to plot spectral density.
Test single evaluation and plot phase and frequency time series, PROVIDE initial condition in ROTATED phase space!
Traceback (most recent call last):
  File "guided_execution.py", line 1784, in <module>
    singleRealization(params)
  File "guided_execution.py", line 921, in singleRealization
    pert, plot_out)
  File "D:\Benutzer\platz\Documents\Professional\Research\Coupled PLLs\github lucas\delayCoupledDPLLnet\case_singleout.py", line 252, in singleout
    data = simulatePllNetwork(mode, topology, couplingfct, F, Nsteps, dt, c, Fc, F_Omeg, K, N, k, delay, phiS, phiM, domega, diffconstK, cLF, Nx, Ny, kx, ky, plot_Phases_Freq) # initiates simulation and saves result in results container
UnboundLocalError: local variable 'phiM' referenced before assignment

**Comment by cuichi23** [comment]
ok, phiM was not set for global coupling -- added that
